## MGSC 695 - Optimization for Data Science

### Python Code for Problem 2

#### Submitted by : Jared Balakrishnan
#### McGill ID: 261175926

In [36]:
from pathlib import Path 
import pandas as pd 
import numpy as np

In [37]:
dataset_path: Path =  Path().absolute() / "datasets"

In [38]:
def read_dataset(file_path: Path) -> pd.DataFrame:

    return pd.read_csv(file_path)

In [39]:
advertising_df = read_dataset(dataset_path / "advertising.csv")

In [40]:
advertising_df.head(5)

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [41]:
Y = advertising_df['Sales']                                 # isolating the target / outcome variable
X = advertising_df.drop(['Unnamed: 0', 'Sales'], axis = 1)  # isolating the predictors

In [42]:
X.head()

TV  Radio  Newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [43]:
X['Intercept'] = 1

X = X[['Intercept', 'TV', 'Radio', 'Newspaper']]

In [44]:
X_matrix = X.to_numpy()

In [45]:
X_matrix

array([[  1. , 230.1,  37.8,  69.2],
       [  1. ,  44.5,  39.3,  45.1],
       [  1. ,  17.2,  45.9,  69.3],
       [  1. , 151.5,  41.3,  58.5],
       [  1. , 180.8,  10.8,  58.4],
       [  1. ,   8.7,  48.9,  75. ],
       [  1. ,  57.5,  32.8,  23.5],
       [  1. , 120.2,  19.6,  11.6],
       [  1. ,   8.6,   2.1,   1. ],
       [  1. , 199.8,   2.6,  21.2],
       [  1. ,  66.1,   5.8,  24.2],
       [  1. , 214.7,  24. ,   4. ],
       [  1. ,  23.8,  35.1,  65.9],
       [  1. ,  97.5,   7.6,   7.2],
       [  1. , 204.1,  32.9,  46. ],
       [  1. , 195.4,  47.7,  52.9],
       [  1. ,  67.8,  36.6, 114. ],
       [  1. , 281.4,  39.6,  55.8],
       [  1. ,  69.2,  20.5,  18.3],
       [  1. , 147.3,  23.9,  19.1],
       [  1. , 218.4,  27.7,  53.4],
       [  1. , 237.4,   5.1,  23.5],
       [  1. ,  13.2,  15.9,  49.6],
       [  1. , 228.3,  16.9,  26.2],
       [  1. ,  62.3,  12.6,  18.3],
       [  1. , 262.9,   3.5,  19.5],
       [  1. , 142.9,  29.3,  12.6],
 

In [46]:
X_matrix_transposed = X_matrix.transpose()

In [47]:
print(f"Shape of X: {X_matrix.shape[0]} x {X_matrix.shape[1]}")
print(f"Shape of X^T: {X_matrix_transposed.shape[0]} x {X_matrix_transposed.shape[1]}")

Shape of X: 200 x 4
Shape of X^T: 4 x 200


In [48]:
X_T_X = (X_matrix_transposed) @ (X_matrix)

X_T_X_inv = np.linalg.inv(X_T_X)

X_T_y = (X_matrix_transposed) @ Y

In [49]:
beta_predicted = X_T_X_inv @ X_T_y

In [50]:
beta_predicted

array([ 2.93888937e+00,  4.57646455e-02,  1.88530017e-01, -1.03749304e-03])

In [51]:
beta_df = pd.DataFrame(beta_predicted, columns=['Matrix Algebra'])

In [52]:
beta_df

Matrix Algebra
0        2.938889
1        0.045765
2        0.188530
3       -0.001037

## Blackbox Linear Regression Implementation

In [69]:
from sklearn.linear_model import LinearRegression

regression = LinearRegression(fit_intercept = True).fit(X_matrix[:,1:], Y)

In [70]:
regression.coef_

array([ 0.04576465,  0.18853002, -0.00103749])

In [73]:
regression.intercept_

2.9388893694594014

In [77]:
blackbox = np.insert(regression.coef_, 0, regression.intercept_)

In [78]:
blackbox

array([ 2.93888937e+00,  4.57646455e-02,  1.88530017e-01, -1.03749304e-03])

In [79]:
blackbox_beta = pd.DataFrame(blackbox, columns = ['Blackbox Implementation'])

In [80]:
blackbox_beta

Blackbox Implementation
0                 2.938889
1                 0.045765
2                 0.188530
3                -0.001037

## Comparing the Coefficients

In [81]:
coefficients = pd.concat([beta_df, blackbox_beta], axis = 1)

In [82]:
coefficients

Matrix Algebra  Blackbox Implementation
0        2.938889                 2.938889
1        0.045765                 0.045765
2        0.188530                 0.188530
3       -0.001037                -0.001037

In [83]:
coefficients['delta'] = coefficients['Matrix Algebra'] - coefficients['Blackbox Implementation']

In [84]:
coefficients

Matrix Algebra  Blackbox Implementation         delta
0        2.938889                 2.938889 -1.953993e-14
1        0.045765                 0.045765 -9.714451e-17
2        0.188530                 0.188530 -1.165734e-15
3       -0.001037                -0.001037  3.224417e-16

In [86]:
print(coefficients.to_markdown())
print("Please note Coefficient 0 refers to the intercept!")

|    |   Matrix Algebra |   Blackbox Implementation |        delta |
|---:|-----------------:|--------------------------:|-------------:|
|  0 |       2.93889    |                2.93889    | -1.95399e-14 |
|  1 |       0.0457646  |                0.0457646  | -9.71445e-17 |
|  2 |       0.18853    |                0.18853    | -1.16573e-15 |
|  3 |      -0.00103749 |               -0.00103749 |  3.22442e-16 |
Please note Coefficient 0 refers to the intercept!
